CREATE TABLE TB_MENU (
    MENU_CODE VARCHAR2(20) NOT NULL,
    MENU_NAME VARCHAR2(30) NOT NULL,
    PROG_PATH VARCHAR2(100) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    CREATED_BY VARCHAR2(50),
    UPDATE_DATE DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    CONSTRAINT PK_TB_MENU PRIMARY KEY (MENU_CODE)
);

COMMENT ON COLUMN TB_MENU.MENU_CODE IS '�޴��ڵ�';
COMMENT ON COLUMN TB_MENU.MENU_NAME IS '�޴���';
COMMENT ON COLUMN TB_MENU.PROG_PATH IS '���α׷� ���';
COMMENT ON COLUMN TB_MENU.CREATE_DATE IS '��������';
COMMENT ON COLUMN TB_MENU.CREATED_BY IS '������';
COMMENT ON COLUMN TB_MENU.UPDATE_DATE IS '��������';
COMMENT ON COLUMN TB_MENU.UPDATED_BY IS '������';


CREATE TABLE TB_USER (
    USER_ID VARCHAR2(50) NOT NULL,
    USER_NAME VARCHAR2(50) NOT NULL,
    NICKNAME VARCHAR2(100) NOT NULL,
    BIRTH CHAR(6) NOT NULL,
    IDENTI CHAR(7) NOT NULL,
    EMAIL VARCHAR2(200),
    PHONE VARCHAR2(20),
    ADDRESS VARCHAR2(100),
    ADDRESSDETAIL VARCHAR2(300),
    CREATE_DATE DATE DEFAULT SYSDATE,
    CREATED_BY VARCHAR2(50),
    UPDATE_DATE DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    CONSTRAINT PK_TB_USER PRIMARY KEY (USER_ID)
);

COMMENT ON COLUMN TB_USER.USER_ID IS '�����ID';
COMMENT ON COLUMN TB_USER.USER_NAME IS '����� �̸�';
COMMENT ON COLUMN TB_USER.NICKNAME IS '�г���';
COMMENT ON COLUMN TB_USER.BIRTH IS '�������';
COMMENT ON COLUMN TB_USER.IDENTI IS '�ֹι�ȣ ���ڸ�';
COMMENT ON COLUMN TB_USER.EMAIL IS '�̸���';
COMMENT ON COLUMN TB_USER.PHONE IS '��ȭ��ȣ';
COMMENT ON COLUMN TB_USER.ADDRESS IS '�ּ�';
COMMENT ON COLUMN TB_USER.ADDRESSDETAIL IS '�ּһ�';
COMMENT ON COLUMN TB_USER.CREATE_DATE IS '��������';
COMMENT ON COLUMN TB_USER.CREATED_BY IS '������';
COMMENT ON COLUMN TB_USER.UPDATE_DATE IS '��������';
COMMENT ON COLUMN TB_USER.UPDATED_BY IS '������';


CREATE TABLE TB_ITEM (
    ITEM_CODE VARCHAR2(30) NOT NULL,
    ITEM_NAME VARCHAR2(100) NOT NULL,
    SALE_PRICE NUMBER DEFAULT 0,
    PRICE NUMBER DEFAULT 0,
    STAR_POINT NUMBER DEFAULT 0,
    DELIVERY VARCHAR2(20),
    DELIVERY_PRICE NUMBER,
    DESCRIPTION VARCHAR2(3000),
    CREATE_DATE DATE DEFAULT SYSDATE,
    CREATED_BY VARCHAR2(50),
    UPDATE_DATE DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    CONSTRAINT PK_TB_ITEM PRIMARY KEY (ITEM_CODE)
);

COMMENT ON COLUMN TB_ITEM.ITEM_CODE IS '��ǰ�ڵ�';
COMMENT ON COLUMN TB_ITEM.ITEM_NAME IS '��ǰ��';
COMMENT ON COLUMN TB_ITEM.SALE_PRICE IS '���δܰ�';
COMMENT ON COLUMN TB_ITEM.PRICE IS '�ܰ�';
COMMENT ON COLUMN TB_ITEM.STAR_POINT IS '����';
COMMENT ON COLUMN TB_ITEM.DELIVERY IS '�������';
COMMENT ON COLUMN TB_ITEM.DELIVERY_PRICE IS '��ۺ�';
COMMENT ON COLUMN TB_ITEM.DESCRIPTION IS '��ǰ �󼼼���';
COMMENT ON COLUMN TB_ITEM.CREATE_DATE IS '��������';
COMMENT ON COLUMN TB_ITEM.CREATED_BY IS '������';
COMMENT ON COLUMN TB_ITEM.UPDATE_DATE IS '��������';
COMMENT ON COLUMN TB_ITEM.UPDATED_BY IS '������';


CREATE TABLE TB_ITEM_SPEC (
    ITEM_CODE VARCHAR2(30) NOT NULL,
    SPEC_CODE VARCHAR2(30) NOT NULL,
    SPEC_NAME VARCHAR2(100) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    CREATED_BY VARCHAR2(50),
    UPDATE_DATE DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    CONSTRAINT PK_TB_ITEM_SPEC PRIMARY KEY (ITEM_CODE, SPEC_CODE),
    CONSTRAINT FK_ITEM_SPEC_ITEM FOREIGN KEY (ITEM_CODE) REFERENCES TB_ITEM(ITEM_CODE)
);

COMMENT ON COLUMN TB_ITEM_SPEC.ITEM_CODE IS '��ǰ�ڵ�';
COMMENT ON COLUMN TB_ITEM_SPEC.SPEC_CODE IS '�����ڵ�';
COMMENT ON COLUMN TB_ITEM_SPEC.SPEC_NAME IS '�����';
COMMENT ON COLUMN TB_ITEM_SPEC.CREATE_DATE IS '��������';
COMMENT ON COLUMN TB_ITEM_SPEC.CREATED_BY IS '������';
COMMENT ON COLUMN TB_ITEM_SPEC.UPDATE_DATE IS '��������';
COMMENT ON COLUMN TB_ITEM_SPEC.UPDATED_BY IS '������';


CREATE TABLE TB_ITEM_REVIEW (
    REVIEW_SEQ NUMBER NOT NULL,
    ITEM_CODE VARCHAR2(30) NOT NULL,
    STAR_POINT NUMBER DEFAULT 0,
    REVIEWDETAIL VARCHAR2(3000),
    CREATE_DATE DATE DEFAULT SYSDATE,
    CREATED_BY VARCHAR2(50),
    UPDATE_DATE DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    CONSTRAINT PK_TB_ITEM_REVIEW PRIMARY KEY (REVIEW_SEQ),
    CONSTRAINT FK_ITEM_REVIEW_ITEM FOREIGN KEY (ITEM_CODE) REFERENCES TB_ITEM(ITEM_CODE)
);

COMMENT ON COLUMN TB_ITEM_REVIEW.REVIEW_SEQ IS '�����ȣ';
COMMENT ON COLUMN TB_ITEM_REVIEW.ITEM_CODE IS '��ǰ�ڵ�';
COMMENT ON COLUMN TB_ITEM_REVIEW.STAR_POINT IS '����';
COMMENT ON COLUMN TB_ITEM_REVIEW.REVIEWDETAIL IS '���� ��';
COMMENT ON COLUMN TB_ITEM_REVIEW.CREATE_DATE IS '��������';
COMMENT ON COLUMN TB_ITEM_REVIEW.CREATED_BY IS '������';
COMMENT ON COLUMN TB_ITEM_REVIEW.UPDATE_DATE IS '��������';
COMMENT ON COLUMN TB_ITEM_REVIEW.UPDATED_BY IS '������';


CREATE TABLE TB_ITEM_REVIEW_IMAGE (
    REVIEW_SEQ NUMBER NOT NULL,
    REVIEW_IMAGE VARCHAR2(100),
    CREATE_DATE DATE DEFAULT SYSDATE,
    CREATED_BY VARCHAR2(50),
    UPDATE_DATE DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    CONSTRAINT FK_ITEM_REVIEW_IMAGE_REVIEW FOREIGN KEY (REVIEW_SEQ) REFERENCES TB_ITEM_REVIEW(REVIEW_SEQ)
);

COMMENT ON COLUMN TB_ITEM_REVIEW_IMAGE.REVIEW_SEQ IS '���� ��ȣ';
COMMENT ON COLUMN TB_ITEM_REVIEW_IMAGE.REVIEW_IMAGE IS '���� �̹���';
COMMENT ON COLUMN TB_ITEM_REVIEW_IMAGE.CREATE_DATE IS '��������';
COMMENT ON COLUMN TB_ITEM_REVIEW_IMAGE.CREATED_BY IS '������';
COMMENT ON COLUMN TB_ITEM_REVIEW_IMAGE.UPDATE_DATE IS '��������';
COMMENT ON COLUMN TB_ITEM_REVIEW_IMAGE.UPDATED_BY IS '������';


CREATE TABLE TB_ITEM_IMAGE (
    ITEM_CODE VARCHAR2(30),
    ITEM_IMAGE VARCHAR2(100),
    CREATE_DATE DATE DEFAULT SYSDATE,
    CREATED_BY VARCHAR2(50),
    UPDATE_DATE DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    CONSTRAINT FK_ITEM_IMAGE_ITEM FOREIGN KEY (ITEM_CODE) REFERENCES TB_ITEM(ITEM_CODE)
);

COMMENT ON COLUMN TB_ITEM_IMAGE.ITEM_CODE IS '��ǰ�ڵ�';
COMMENT ON COLUMN TB_ITEM_IMAGE.ITEM_IMAGE IS '��ǰ�̹���';
COMMENT ON COLUMN TB_ITEM_IMAGE.CREATE_DATE IS '��������';
COMMENT ON COLUMN TB_ITEM_IMAGE.CREATED_BY IS '������';
COMMENT ON COLUMN TB_ITEM_IMAGE.UPDATE_DATE IS '��������';
COMMENT ON COLUMN TB_ITEM_IMAGE.UPDATED_BY IS '������';


CREATE TABLE TB_BASKET (
    USER_ID VARCHAR2(50),
    ITEM_CODE VARCHAR2(30),
    ITEM_QTY NUMBER,
    CREATE_DATE DATE DEFAULT SYSDATE,
    CREATED_BY VARCHAR2(50),
    UPDATE_DATE DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    CONSTRAINT FK_BASKET_USER FOREIGN KEY (USER_ID) REFERENCES TB_USER(USER_ID),
    CONSTRAINT FK_BASKET_ITEM FOREIGN KEY (ITEM_CODE) REFERENCES TB_ITEM(ITEM_CODE)
);

COMMENT ON COLUMN TB_BASKET.USER_ID IS '�����ID';
COMMENT ON COLUMN TB_BASKET.ITEM_CODE IS '��ǰ�ڵ�';
COMMENT ON COLUMN TB_BASKET.ITEM_QTY IS '��ǰ����';
COMMENT ON COLUMN TB_BASKET.CREATE_DATE IS '��������';
COMMENT ON COLUMN TB_BASKET.CREATED_BY IS '������';
COMMENT ON COLUMN TB_BASKET.UPDATE_DATE IS '��������';
COMMENT ON COLUMN TB_BASKET.UPDATED_BY IS '������';


CREATE TABLE TB_SIGNKEY (
    USER_ID VARCHAR2(50),
    SIGNKEY CHAR(6),
    CONSTRAINT FK_SIGNKEY_USER FOREIGN KEY (USER_ID) REFERENCES TB_USER(USER_ID)
);

COMMENT ON COLUMN TB_SIGNKEY.USER_ID IS '�����ID';
COMMENT ON COLUMN TB_SIGNKEY.SIGNKEY IS '����Ű';


CREATE TABLE TB_LAST_ITEM (
    USER_ID VARCHAR2(50),
    ITEM_CODE VARCHAR2(30),
    CREATE_DATE DATE DEFAULT SYSDATE,
    CREATED_BY VARCHAR2(50),
    UPDATE_DATE DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    CONSTRAINT FK_LAST_ITEM_USER FOREIGN KEY (USER_ID) REFERENCES TB_USER(USER_ID),
    CONSTRAINT FK_LAST_ITEM_ITEM FOREIGN KEY (ITEM_CODE) REFERENCES TB_ITEM(ITEM_CODE)
);

COMMENT ON COLUMN TB_LAST_ITEM.USER_ID IS '�����ID';
COMMENT ON COLUMN TB_LAST_ITEM.ITEM_CODE IS '��ǰ�ڵ�';
COMMENT ON COLUMN TB_LAST_ITEM.CREATE_DATE IS '��������';
COMMENT ON COLUMN TB_LAST_ITEM.CREATED_BY IS '������';
COMMENT ON COLUMN TB_LAST_ITEM.UPDATE_DATE IS '��������';
COMMENT ON COLUMN TB_LAST_ITEM.UPDATED_BY IS '������';


CREATE TABLE TB_ORDER (
    ORDER_NO NUMBER NOT NULL,
    USER_ID VARCHAR2(50),
    ORDER_DATE DATE,
    CREATE_DATE DATE DEFAULT SYSDATE,
    CREATED_BY VARCHAR2(50),
    UPDATE_DATE DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    CONSTRAINT PK_TB_ORDER PRIMARY KEY (ORDER_NO),
    CONSTRAINT FK_ORDER_USER FOREIGN KEY (USER_ID) REFERENCES TB_USER(USER_ID)
);

COMMENT ON COLUMN TB_ORDER.ORDER_NO IS '�ֹ���ȣ';
COMMENT ON COLUMN TB_ORDER.USER_ID IS '�����ID';
COMMENT ON COLUMN TB_ORDER.ORDER_DATE IS '�ֹ�����';
COMMENT ON COLUMN TB_ORDER.CREATE_DATE IS '��������';
COMMENT ON COLUMN TB_ORDER.CREATED_BY IS '������';
COMMENT ON COLUMN TB_ORDER.UPDATE_DATE IS '��������';
COMMENT ON COLUMN TB_ORDER.UPDATED_BY IS '������';


CREATE TABLE TB_ORDERDETAIL (
    ORDER_NO NUMBER NOT NULL,
    ORDERDETAIL_NO NUMBER NOT NULL,
    ITEM_CODE VARCHAR2(30),
    ITEM_QTY NUMBER,
    ITEM_PRICE NUMBER,
    CREATE_DATE DATE DEFAULT SYSDATE,
    CREATED_BY VARCHAR2(50),
    UPDATE_DATE DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(50),
    CONSTRAINT PK_TB_ORDERDETAIL PRIMARY KEY (ORDER_NO, ORDERDETAIL_NO),
    CONSTRAINT FK_ORDERDETAIL_ORDER FOREIGN KEY (ORDER_NO) REFERENCES TB_ORDER(ORDER_NO),
    CONSTRAINT FK_ORDERDETAIL_ITEM FOREIGN KEY (ITEM_CODE) REFERENCES TB_ITEM(ITEM_CODE),
);

COMMENT ON COLUMN TB_ORDERDETAIL.ORDER_NO IS '�ֹ���ȣ';
COMMENT ON COLUMN TB_ORDERDETAIL.ORDERDETAIL_NO IS '�ֹ��󼼹�ȣ';
COMMENT ON COLUMN TB_ORDERDETAIL.ITEM_CODE IS '��ǰ�ڵ�';
COMMENT ON COLUMN TB_ORDERDETAIL.ITEM_QTY IS '�ֹ�����';
COMMENT ON COLUMN TB_ORDERDETAIL.ITEM_PRICE IS '��ǰ�ǸŴܰ�';
COMMENT ON COLUMN TB_ORDERDETAIL.CREATE_DATE IS '��������';
COMMENT ON COLUMN TB_ORDERDETAIL.CREATED_BY IS '������';
COMMENT ON COLUMN TB_ORDERDETAIL.UPDATE_DATE IS '��������';
COMMENT ON COLUMN TB_ORDERDETAIL.UPDATED_BY IS '������';
